sudo: false
language: ruby
cache: bundler
rvm:
- 2.4
bundler_args: --without system_tests
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/centos-7
      script: bundle exec rake task_acceptance
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-14.04
      script: bundle exec rake task_acceptance
      services: docker
      sudo: required
    -
      env: CHECK=spec rubocop metadata_lint check:git_ignore check:dot_underscore check:test_file
    -
      env: CHECK=spec
      rvm: 2.3
